# Generated by Django 3.1.7 on 2021-09-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210912_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.IntegerField(),
        ),
    ]
