# Generated by Django 3.1.7 on 2021-09-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210912_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(unique=True),
        ),
    ]
