# Generated by Django 3.1.7 on 2021-11-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_article_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(height_field=100, null=True, upload_to=None, width_field=150),
        ),
    ]
