# Generated by Django 3.1.7 on 2021-11-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_auto_20211126_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
