# Generated by Django 3.1.7 on 2021-09-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
    ]
