# Generated by Django 3.1.7 on 2021-09-19 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0008_auto_20210917_2052'),
        ('threads', '0005_auto_20210918_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='articles',
            field=models.ManyToManyField(null=True, to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='authors',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
